.\" Manpage for isocmd
.TH ISOCMD 1 "December 2024" "1.0" "isocmd manual"
.SH NAME
isocmd \- A brief description of what isocmd does
.SH SYNOPSIS
.B isocmd
[\fIOPTIONS\fR] \fIarguments\fR
.SH DESCRIPTION
\&isocmd is a tool for ... (describe the purpose of the program).

.SH OPTIONS
.TP
.B \-h, \-\-help
Display help information and exit.
.TP
.B \-v, \-\-version
Show the version of the program.
.TP
.B \-f, \-\-file \fIfilename\fR
Specify the input file for processing.
.TP
.B \-o, \-\-output \fIfilename\fR
Set the output file name.
.TP
.B \-r, \-\-remove
Remove the specified file after processing.

.SH EXAMPLES
.TP
.B "isocmd \-f input.iso \-o output.iso"
Run the command with the specified input and output files.
.TP
.B "isocmd \-h"
Display help information for the program.

.SH SEE ALSO
.BR ls (1),
.BR cp (1)
.SH AUTHOR
Written by [Your Name].
.SH BUGS
Report bugs to [Your Contact Information].
